import 'package:cloud_firestore/cloud_firestore.dart';

class DatabaseMethods {
  //used to search in the search screen
  getUserByUsername(String username) async {
    return await FirebaseFirestore.instance
        .collection("users")
        .where("name", isEqualTo: username)
        .get();
        //find the documents inside the "users" collection that has the value of the "name" key

  }

  getUserByEmail(String userEmail) async {
    return await FirebaseFirestore.instance
        .collection("users")
        .where("email", isEqualTo: userEmail)
        .get();
        //used when signing in to get the document of the user signing in so that the 
        //users username can be saved locally
  }

  uploadUserInfo(userMap) {
    FirebaseFirestore.instance.collection("users").add(userMap).catchError((e) {
      print(e.toString());
    });
    //.add() can be used in place of .doc().set
    //it's just that we are not giving ID's(names) to the documents we are adding to
    //but i think its autogenerated
  }

  createChatRoom(String chatRoomId, chatRoomMap) {
    FirebaseFirestore.instance
        .collection("ChatRoom")
        .doc(chatRoomId)
        .set(chatRoomMap)
        .catchError((e) {
      print(e.toString());
    });
  }

  addConversationMessages(String? chatRoomId, messageMap) {
    FirebaseFirestore.instance
        .collection("ChatRoom")
        .doc(chatRoomId)
        .collection("chats")
        .add(messageMap)
        .catchError((e) {
      print(e.toString());
    });
  }

  // getConversationMessages(String? chatRoomId) async {
  //   return await FirebaseFirestore.instance
  //       .collection("ChatRoom")
  //       .doc(chatRoomId)
  //       .collection("chats")
  //       .snapshots();
  // }

  // getChatRooms(String userName) {
  //   FirebaseFirestore.instance
  //       .collection("ChatRoom")
  //       .where("users", arrayContains: userName)
  //       .snapshots();
  // }
}
